name: flutter_carplay
description: Flutter Apps are now on Apple CarPlay. This package aims to make it safe to use iPhone apps made with Flutter in the car by integrating with CarPlay.
version: 1.2.0
homepage: https://github.com/RedC4ke/flutter_carplay#readme
repository: https://github.com/RedC4ke/flutter_carplay
issue_tracker: https://github.com/RedC4ke/flutter_carplay/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlugin
